### ISSUE TITLE
firefox OS

### ISSUE THREAD

**Issue by paskalito** [Anon215/privacytools.it-sec.rocks#15]
wird ja nicht mehr weiterentwickelt..

sollen wir das einfach entfernen?

btw. ne eigene rubrik für fdroid wäre vlt. gut.

bzw auch 
https://www.kuketz-blog.de/your-phone-your-data-light-android-unter-kontrolle/

die android unter kontrolle serie.

**Comment by cwcopa** [comment]
Hey, FirefoxOS hatten wir schon auf dem Zettel und wird wohl mit dem nächsten Update entfernt. Danke für den Tipp.

Zum Rest: Wir schauen mal, ob sich dies sinnvoll einbauen lässt.

**Comment by Anon215** [comment]
Hallo peskalito,

ich finde den Vorschlag recht gut und habe selbst auch schon überlegt, wie sich Fremdquellen konsistent einbinden lassen.
Gerade Mike (Kuketz) macht hier sehr informative und gute Artikel, was für den deutschsprachigen Raum toll ist und besser auf die hiesigen Datenschutz und Privatsphäre Gegebenheiten besser zutrifft als (übersetzte) Artikel aus den USA.

Auch gibt es sehr schöne Videos (Erklärvideos und Aufklärung als Stiftfilm oder Doku), die ich gern mit verlinken oder einbetten wollen würde.
Hier muss ich noch eine Aufwandsschätzung vornehmen und es gilt zu klären, ob und wie das dann umgesetzt wird.
Grundsätzlich wäre es auch denkbar, dass hieraus ein gänzlich neues Projekt entsteht oder das ein zweites Projekt mit diesem hier verknüpft wird.
(Hauptsächlich dadurch bedingt, weil ich denke das man dann nicht mehr alles auf nur einer Seite präsentieren kann, sondern es müsste die komplette Struktur der Seite überarbeiten und ggf mit Subpages gearbeitet werden.)

Ich hoffe heute noch eine Diskussionsplattform zum Projekt aufgesetzt zu bekommen.
Dort werden dann derartige Vorschläge besprochen.
Wenn es mit der Plattform soweit ist werde ich das auch hier kommunizieren.

Grundsätzlich finde ich in deinem Beitrag hier die wir Form auch sehr schön. :)
Danke, dass du dich beteiligst und für deine Mithilfe am Projekt!

cwcopa und ich stehen in regelmäßigem Austausch mit einander.
Wenn du magst kannst du dich gern aktiv an diesem beteiligen. Details folgen dann.

**Comment by paskalito** [comment]
@Anon215  hey vielen dank für dine gedanken

ich denke auch das die ganze seite jetzt schon extrem lange ist. ich preise sie deswegen auch immer als. "hier ist eine extrem gute und lange seite für mögliche alle möglichen bereiche" bzw. alles.

ehm ich glaube da sich mein leben mittlerweile so weitgehend fern von computer abspielt, und ich regeneration als freizeitbeschäftigung schon als notwendiger teil meiner arbeit verstehe. wird es am sinnvollsten sein wenn ich mich so über github oder eine evtl andere plattform einfach immer dann einbringe wenn ich was zu sagen und zeit dafür habe. das ist leider ziemlich selten der fall und auch sehr schwankend. aber wie sich gezeigt hat werde ich wohl weiterhin immer wieder drüber stolpern. vor allem im bereich xmpp :)

**Comment by cwcopa** [comment]
Kann wohl geschlossen werden.
