### ISSUE TITLE
Please add a link to privacytools.io on your main website

### ISSUE THREAD

**Issue by privacytoolsIO** [Anon215/privacytools.it-sec.rocks#2]
Hi guys,

I was pleased to see a german version of privacytools.io and I support your idea very much. Please let me know if I can help you in any way.

Please add a link to www.privacytools.io on your main website to give credit.

Thanks a lot

**Comment by Anon215** [comment]
Hi :)

Of course, we'll do so.
Still under heavy development.
Also it was planned just to fork your repo but german websites need more adjustments and legal requirements (such as imprint and privacy policy), unfortunately.
At the moment I'm thinking about how to avoid giving my personal data away for everyone but being legal.

**Comment by Anon215** [comment]
Does the credit fit your needs or have you thought about anything different? :)

**Comment by privacytoolsIO** [comment]
Thanks for the credits.

> but german websites need more adjustments and legal requirements

I think that only applies if the owner is based in germany, not because the website is using the german language. Think about hosting outside germany, use cloudflare ssl and whois protection.

**Comment by danielschubert** [comment]
I don't see any problem hosting the site in germany, besides the need of an imprint. but I even doubt we need an imprint, as this site very obviously has no commercial context at all. SSL would be nice though...

**Comment by Anon215** [comment]
Eigentlich können wir auch deutsch schreiben, Maintainer von privacytools.io spricht auch deutsch. :)
Sind damit alle einverstanden?

@privacytoolsIO : Ich kann das Gruppenchatproblem (qTox) übrigens bestätigen.

@danielschubert : ich glaube laut TMG ist es meines Wissens mittlerweile unerheblich, ob die Seite gewerblich genutzt wird oder nur informativen Zwecken gillt.
Allerdings habe ich vorerst mal eine Kontakt-Email Adresse angegeben und für den Rest sage ich mal so: ich arbeite daran, dass es bei der Emailadresse bleibt. 
Was meinst du mit SSL? Haben wir doch. --> https://www.ssllabs.com/ssltest/analyze.html?d=privacytools.it-sec.rocks&s=213.136.82.197

Falls wir nach wie vor Bedarf an einer Gruppendiskussion haben kann ich eine XMPP Gruppe stellen und euch einladen.

**Comment by danielschubert** [comment]
mein diasproa pod hat techn. probleme. laß uns geren per jabber sprechen: x2ero@jabber.danletard.de

**Comment by rugk** [comment]
Der Link zur Hauptseite ist aber schon sehr versteckt. Nur in der Sprachauswahl oben und ganz unten ein kleiner Link.

**Comment by Anon215** [comment]
Der "Hauptseite" war ordentlich und gut sichtbar Gebühr getragen.
Nichts desto Trotz habe ich das Projekt -mit Bannerbild- verlinkt gehabt (im Quellcode wäre das zu sehen gewesen).
Leider hat privacytools.io mehrmals den Aufbau geändert.
So gab es erstmal Probleme mit dem CDN, weswegen ich das Logo direkt von Github geladen habe.
Leider funktioniert auch das nicht mehr, die Seite ist unter neuer Adresse gehostet und bei mir wurde nur noch der Bildtext angezeigt.

Da ich mich größtenteils allein um die Seite kümmere und neben dem Job auch meinem Familienleben nachgehe bin ich auf nette Hinweise angewiesen.
Wohlwollend nehme ich deinen Beitrag hier mal als freundlichen Hinweis wahr und habe das Banner für privacytools.io wieder repariert.
Diesmal sollte es auch nicht mehr kaputt gehen können.

Übrigens unterscheidet sich die deutsche Seite zum Teil entscheident in Inhalt und Aufbau von den anderen Partnerseiten. ;)
