### ISSUE TITLE
https://www.ghostmail.com/  is closed for normal users

### ISSUE THREAD

**Issue by paskalito** [Anon215/privacytools.it-sec.rocks#4]
they only support companies from now on

https://www.ghostmail.com/info

**Comment by Anon215** [comment]
Das habe ich im Repo von privacytools.io bereits gelesen und werde das abändern.
Habe eh ein paar Verbesserungen geplant.

Danke dir.

**Comment by Anon215** [comment]
Okay, habe ich gerade überarbeitet und Ghostmail raus genommen.
Geht dann mit dem nächsten Sync online.

**Comment by paskalito** [comment]
besten dank
