### ISSUE TITLE
conversations und omemo sollten die messenger sektion anführen

### ISSUE THREAD

**Issue by paskalito** [Anon215/privacytools.it-sec.rocks#5]
https://www.kuketz-blog.de/conversations-sicherer-android-messenger/
 mit anderen worten erkenntnisse von dem blogeintrag sollten in diese tolle seite einfliessen.

**Comment by Anon215** [comment]
Hallo paskalito, das sehe ich genauso und ich werde das asap anpassen. :)
Danke für deine Beteiligung und die Kritik.

Freue mich immer über Beteiligung. _thumbs up_

**Comment by Anon215** [comment]
Okay, habe den Bereich überarbeitet.

Bedauerlich ist immer wieder, dass es Conversations nur für Android gibt.
Da zukünftig aber auch ChatSecure mit omemo nachziehen will habe ich das entsprechend vermekt.

**Comment by paskalito** [comment]
Immer sehr gern vielen dank für deine arbeit ! bin froh darum!
der vermerk ist sehr gut. (schön das sie jetzt darauf fokussieren ( wusste nichts von einem ilzenzproblem (aber wenn man ios benutzt.. - sowieso ziemlich witzlos alles naja))) wollte noch vorschlagen diesen link
https://www.kuketz-blog.de/conversations-sicherer-android-messenger/

irgendwie da zu integrieren weil er hald sehr gut geschrieben ist und für normalos sehr gut verständlich ist. ( auch gleich einen haufen hintergrund infos liefert)
