### ISSUE TITLE
Added link to your german version

### ISSUE THREAD

**Issue by privacytoolsIO** [Anon215/privacytools.it-sec.rocks#8]
hi guys,

i've just added a link to your german version in our header area: https://www.privacytools.io/

please feel free to link to the english and spanish version if you like.

btw, are you planning on updating the german website? 

thanks for keeping up the good work.

bye

**Comment by Anon215** [comment]
Hi,

thanks a lot for adding a link to our site! Really appreciate that.

I already added a link to your project a while ago but maybe I should place that more prominent (footer -> header).

Sadly I'm alone here, there is no other person taking care of the project "frequently".
I'm following the discussions at your project and change things every now and then.

Have to try to reach out for more Contributors / Supporters.
Without "classic" social media sites this is kinda hard but I will give it a try.

thank you, too

**Comment by privacytoolsIO** [comment]
>I already added a link to your project a while ago but maybe I should place that more prominent (footer -> header).

This is our solution for the moment: 
<img width="675" alt="screenshot" src="https://cloud.githubusercontent.com/assets/11730911/21559245/b9d4756c-ce83-11e6-8ce3-8447cd38a63e.png">

> Without "classic" social media sites this is kinda hard but I will give it a try.

Why not include classic social media sites in your share options? The main source of traffic of privacytools.io is reddit, Twitter and Facebook. From my experience it's why easier to promote an ad free project like this, so you can just go ahead and post your link everywhere privacy related.

> Have to try to reach out for more Contributors / Supporters.

I hope the more visible links to your german version on privacytools.io will help to drive more traffic towards you.

Btw, you can add me on Wire(.com) my username is @burunghantu

**Comment by Anon215** [comment]
Hi, I adopted your solution for speech selection.

I avoid the use of Facebook, Twitter and Co by any means.
This is from conviction.
I will give reddit a try soon and add you at wire.com
